services:
  nikl-pkg-mgr:
    # The image is available on private docker hub, you can use your own image if you have built it
    image: neko7nik/nikl-pkg-mgr:latest
    container_name: nikl-pkg-mgr

    # The environment variables are used to configure the application
    # Use the correct values for the environment variables
    # Change the <xxx> to the correct values to reflect your environment
    environment:
      - TZ=Asia/Kolkata
      
      - GUNICORN_ARG_WORKERS=<Number of workers to be used, normally 2 * number of CPU cores; integer>
      - GUNICORN_ARG_THREADS=<Number of threads to be used, normally 2 * number of workers; integer>
      - GUNICORN_ARG_TIMEOUT=<Timeout for the request; integer>
      - GUNICORN_ARG_BIND_PORT=8086

      - POSTGRES_DB_USERNAME=neko_nik
      - POSTGRES_DB_PASSWORD=Neko-Nik
      - POSTGRES_DB_HOST=nikl-pg-db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_DATABASE=nik_lang
      # The POSTGRES_DB_URI is optional, if provided it will override the other Postgres environment variables
      # - POSTGRES_DB_URI=postgresql://<username>:<password>@<host>:<port>/<database>
      - POSTGRES_POOL_SIZE=10

      - HCAPTCHA_SECRET_KEY=<Your hCaptcha secret key; string>

      - MEMCACHED_DB_HOST=cache-db
      - MEMCACHED_DB_PORT=11211
      - MEMCACHED_DB_POOL_SIZE=10
      # Session expiry time in seconds (default is 3 x 60 x 60 = 10800 = 3 hours)
      - MAX_AGE_OF_CACHE=10800

      # API Logging configuration
      - LOG_LEVEL=20

    # The ports are used to expose the application to the host machine
    ports:
      - "8086:8086" # Note: Make sure it matches with the GUNICORN_ARG_BIND_PORT

    # The volumes are used to store the logs
    # LHS is the host machine path and RHS is the container path
    # Change the LHS to the correct path to store the logs (if required)
    volumes:
      - /var/log/nikl-pkg-mgr-api:/var/log/api

    networks:
      - nikl_pkg_network

    # The restart policy is set to always to restart the container in case of failure
    restart: always

  nikl-pg-db:
    image: postgres:16
    container_name: nikl-pg-db
    environment:
      - POSTGRES_PASSWORD=Neko-Nik
      - POSTGRES_USER=Neko_Nik
      - POSTGRES_DB=nik_lang
    volumes:
      - /data/nikl-pkg-db:/var/lib/postgresql/data
    restart: always
    networks:
      - nikl_pkg_network

  cache-db:
    image: memcached:1.6
    container_name: cache-db
    restart: always
    networks:
      - nikl_pkg_network

networks:
  nikl_pkg_network:
    driver: bridge
